// IaC entrypoint for devops2-endterm.
//
// The Ubuntu VM is provisioned out-of-band (UTM/Multipass/cloud) and exposed at
// var.vm_ip. Terraform owns:
//   1. the canonical inventory (Ansible + Kubespray both read from here)
//   2. the orchestration trigger that runs `ansible-playbook site.yml`
//
// `terraform apply` produces a fully bootstrapped cluster — no more six-step
// shell ritual. Re-runs are idempotent because the underlying Ansible is.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = ">= 2.5.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.2.0"
    }
  }
}

locals {
  repo_root = "${path.module}/.."
}

resource "local_file" "ansible_inventory" {
  filename        = "${local.repo_root}/ansible/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    ; GENERATED BY TERRAFORM — do not edit by hand.
    ; Source: terraform/main.tf → local_file.ansible_inventory
    [vm]
    ${var.vm_hostname} ansible_host=${var.vm_ip} ansible_user=${var.ssh_user} ansible_python_interpreter=/usr/bin/python3

    [vm:vars]
    cluster_vm_ip=${var.vm_ip}
  EOT
}

resource "local_file" "kubespray_inventory" {
  filename        = "${local.repo_root}/bootstrap/kubespray-inventory/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    ; GENERATED BY TERRAFORM — do not edit by hand.
    [kube_control_plane]
    ${var.vm_hostname} ansible_host=${var.vm_ip} ansible_user=${var.ssh_user}

    [etcd]
    ${var.vm_hostname}

    [kube_node]
    ${var.vm_hostname}

    [k8s_cluster:children]
    kube_control_plane
    kube_node
  EOT
}

// One-shot bootstrap: invoke Ansible after inventory has been written.
// Triggered explicitly with `terraform apply -var=run_bootstrap=true` so
// re-plans don't always rerun a 15-minute kubespray.
resource "null_resource" "bootstrap" {
  count = var.run_bootstrap ? 1 : 0

  triggers = {
    inventory_sha = local_file.ansible_inventory.content_sha256
    site_sha      = filesha256("${local.repo_root}/ansible/site.yml")
  }

  provisioner "local-exec" {
    working_dir = "${local.repo_root}/ansible"
    command     = "ansible-playbook -i inventory.ini site.yml"
  }

  depends_on = [
    local_file.ansible_inventory,
    local_file.kubespray_inventory,
  ]
}
