// IaC entrypoint for devops2-endterm.
//
// The Ubuntu VM lives under Multipass on the Mac (see bootstrap/up-vm.sh).
// Terraform owns:
//   1. dynamic IP discovery — `multipass info <name>` is run on every plan,
//      so a new IP (after a `multipass restart` or fresh launch) is picked
//      up with a single `terraform apply`. No file ever hardcodes the IP.
//   2. the canonical inventory (Ansible + Kubespray both read from here)
//   3. the orchestration trigger that runs `ansible-playbook site.yml`
//
// Workflow:
//   bash bootstrap/up-vm.sh                         # launch / resume Multipass VM
//   terraform apply                                 # refresh inventory only
//   terraform apply -var=run_bootstrap=true         # full bootstrap end-to-end
//
// Override path: set `vm_ip` if you ever need to point at a non-Multipass host.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = ">= 2.5.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.2.0"
    }
    external = {
      source  = "hashicorp/external"
      version = ">= 2.3.0"
    }
  }
}

locals {
  repo_root = "${path.module}/.."
  hostname  = var.vm_hostname != "" ? var.vm_hostname : var.vm_name
}

// Auto-discover IP from Multipass on every plan/apply. Bypassed when the user
// passes -var vm_ip=... explicitly (e.g. to target a non-Multipass VM).
data "external" "multipass_ip" {
  count   = var.vm_ip == "" ? 1 : 0
  program = ["${local.repo_root}/scripts/multipass-ip.sh"]
  query = {
    name = var.vm_name
  }
}

locals {
  resolved_ip = var.vm_ip != "" ? var.vm_ip : try(data.external.multipass_ip[0].result.ip, "")
}

// Fail loudly if discovery returns empty — easier to debug than a broken inventory.
resource "terraform_data" "validate_ip" {
  lifecycle {
    precondition {
      condition     = local.resolved_ip != ""
      error_message = "Could not determine VM IP. Either run `bash bootstrap/up-vm.sh` first, or pass -var vm_ip=<ip>."
    }
  }
}

resource "local_file" "ansible_inventory" {
  filename        = "${local.repo_root}/ansible/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    ; GENERATED BY TERRAFORM — do not edit by hand.
    ; Source: terraform/main.tf → local_file.ansible_inventory
    [vm]
    ${local.hostname} ansible_host=${local.resolved_ip} ansible_user=${var.ssh_user} ansible_python_interpreter=/usr/bin/python3

    [vm:vars]
    cluster_vm_ip=${local.resolved_ip}
  EOT
}

resource "local_file" "kubespray_inventory" {
  filename        = "${local.repo_root}/bootstrap/kubespray-inventory/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    ; GENERATED BY TERRAFORM — do not edit by hand.
    [kube_control_plane]
    ${local.hostname} ansible_host=${local.resolved_ip} ansible_user=${var.ssh_user}

    [etcd]
    ${local.hostname}

    [kube_node]
    ${local.hostname}

    [k8s_cluster:children]
    kube_control_plane
    kube_node
  EOT
}

// Ensure a venv with Ansible exists before bootstrap. Idempotent.
// Reuses kubespray/.venv since site.yml populates it for kubespray anyway.
resource "null_resource" "ensure_ansible" {
  count = var.run_bootstrap ? 1 : 0

  triggers = {
    script_sha = filesha256("${local.repo_root}/bootstrap/ensure-ansible.sh")
  }

  provisioner "local-exec" {
    command = "bash ${local.repo_root}/bootstrap/ensure-ansible.sh"
  }
}

// One-shot bootstrap: invoke Ansible after inventory has been written.
// Triggered explicitly with `terraform apply -var=run_bootstrap=true` so
// re-plans don't always rerun a 15-minute kubespray.
resource "null_resource" "bootstrap" {
  count = var.run_bootstrap ? 1 : 0

  triggers = {
    inventory_sha = local_file.ansible_inventory.content_sha256
    site_sha      = filesha256("${local.repo_root}/ansible/site.yml")
  }

  provisioner "local-exec" {
    working_dir = "${local.repo_root}/ansible"
    # Prepend the kubespray venv so ansible-playbook is on PATH even when the
    // user runs terraform from a shell without ansible installed globally.
    // `bash bootstrap/ensure-ansible.sh` provisions that venv on first run.
    command = "PATH=${local.repo_root}/kubespray/.venv/bin:$PATH ansible-playbook -i inventory.ini site.yml"
  }

  depends_on = [
    null_resource.ensure_ansible,
    local_file.ansible_inventory,
    local_file.kubespray_inventory,
  ]
}
