{{- if .Values.fastapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "business.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.fastapi.ingress.className }}
  rules:
    - host: {{ .Values.fastapi.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 80
{{- end }}
