{{- if .Values.fastapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "business.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.fastapi.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.fastapi.ingress.tls.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: {{ .Values.fastapi.ingress.className }}
  {{- if .Values.fastapi.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.fastapi.ingress.host }}
      secretName: fastapi-tls
  {{- end }}
  rules:
    - host: {{ .Values.fastapi.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 80
{{- end }}
