---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: business
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCHOo4OKvTNCAWWZiKfb7SUy6auRt6BZXLWJJkJyX9dwg1JamzErQjFMxz/JNutc4hAuCSbw3oaOFnH+WSx4stcVtXcBvLoSI+9Ev+Hed+Gy/iAZJK9t5tvkuDJOB0FJRcRUuBV/mSeaqgpwtraet136O8ly2lLT6ITECBCf1Eb1yJD9s2t8oJavz2RVbD2DtudMPklyEZsjyOikGAsXNtiSc6icCXAUs+jNopzoCaRQ+mkwkubtKPudpqWWNAAYTHHVXrcJ08q6JUEz5z+MgEFxYv6Ry2wPwiTBl65hBidw7Z36YHL7zZ8hEXSiOHtN+yiGAa62iRsrxUUsdOJLt2RFThSPT4vH9IpqCkVSQmjFtQMMk/S8Iepy9gPzSRH9TKDITizDkkaJLY3lcTWRrfbGO69azxvzXr8wcWn6fJzw3S4jLdQfvqOc2jOINRexgbeP2Wic9oHXSF1I5n5fZikxo9gj3wBC0IrBtURJQjQ2/b/ffjqZ2Bsnt/oLSmtwUplwcutp1R660gOVb4NMNvySWSM4pFo3B20imzwRRwAwi/qyNpRqfv4iicTvmEn9XoPedhI0e2R7JZMttDarWlkXG14ib9dF6wQtQAQUvq6e5rdNPG8jK+pdUOXqHW7459XEPPpA3qW39AvhCUgHqlAPRixgZF5aYwkssX5eav9uS8jbr9j3F5OzBnE7u0oHhCq2qG8MvzinWm/oCtFpjN+EoA6BLq+Zgn67Z5GJNuiag==
    POSTGRES_USER: AgBNETHXyJd6oth5qbCfZc7yLnSwuwDhSOsbLb9aPwPwaTuMSHCAEyz5wnzu6yijQYzhheOsQWVZrr4/3A0Srg7ioKG8E6knAZkhNJxWNe6nSVvtLvctpk1575aOmluLCx0dFpLVKSIcUbB7oPUU9yNMqYAjPaaA2V09N+6QbvvhF1TZWDAs1EsMB1qRiGrRGcQbNBqWH+1amf4b+C8MPU+PnNi1SPVHmytmP1yaCmGatQXsnE3cZ1Yij6D3274J58dtbpysxgW7zLrl3TXhiz/Gfpkffkmm0y87QNgOsNmv21d5m4YW4Cl301IdvXEvtKzM1ma4w0NlLKrQYl+DGiOWEYAeUcbUwYnYpmJIvvT7yUZnBKXpFIGwEdT/v3sIABZIvA9Ui0Q9QXpHESShgLO5HDuB/kHO3N73wcIeOiNI3SdiRaZN4PjL09oA8WMkhvo++XPCrkW6Cbhz+gvlxI+qqxUVjP/BcUffG84PSrponNJ7TjC1PxTFRFKGlU0RIV+BLy0rV9abLJIRVZjZ0f9nLPZiKVpGj3BxmzLbTYykegyt6o2WDwS2oT83lvpmHF3HYOlkgM7C3TJBlFB/6pAabHSfl6EgUc0F2AtZLV5TSr614xTBMAocxz0mJ9TqgAXKwotiNybcpS4BYGtlcPnvJMnGMSrkzyHHJDnYCLovbLUvCts4h7a9bwum2zAceXeL8Zq2TE6H
  template:
    metadata:
      name: db-secret
      namespace: business
