---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: business
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB4auLBviUGLdKaRpIJbt0V6PwecmUs1se04AisyR4R/qDOS4Rp055TcHXGQv0noYR6r0lmc/KUOwWKBFKPR7NugatPv6xD9XVZ9Z9wO9H3MzRPnxAlZVzS45SYnlePDfZsFFKzwgwOfe8J2cgSlXXPH3TZx0TmMM7yfGOmabAIT7NWSKqMHl1XqDrYjR5HK4jbTxklAybK0JjGs9s3Z2FFLYLjdvGJoJmEA9VimZHPbrO9XQk7XmdFxbQMTZuO3UYOosvl7Qfxq+C/w4lSXfpDYdVLs3LGeq9zH94DnObkYo+YabfKg9trML3WTZzw9g/nxBP8/pPMXmkkJP3Bj2TPVsBge+7orxkm7QFG1p/VUTSvzQ+kNogjHiyP1ibfSBttOpo/Hrm6qIWv8gNN0BDf32Cf5fgfR++ttpmW9fMrFI3g9c+W/Dl+e/0tQIrTlLTB9kzIhpPxeVi8H4GgVlz3FtklJQVV++rmY5LREHWVk1cJTBX1WJzBHsMjnACkrYSHo9qlrpE1uTTeeCm/rlfibSrc8dJ0ftzChNVb3YG9MJyKvIR8x12SzA7XOU6LZfiOoRw2jLlb+0MZA3pY5qjoOPV2slbb5yCH0yRNa6+J6/QgSVSZ+ZvIc43uC/Oh+Qpz0atb/BSHaQjsLCQ9xAJQQCf3fxbBrfB/PHFJiWgxbbCqI3bUkE+51qghW2rRpRKijX8EAdCRJUOmZHalMWjwdXTaG2aopUPHY/QHVQ==
    POSTGRES_USER: AgCPFsv3U56jwcWEcxrqHAL6JxVQrkkB9EEp2FJNliZ4P/6VM6QYEt7CAtxvLqAIoXleIXhzHAOQPv0zuvd4rk4GYq7VdbZzGAw7fzKqjgnBdRPQnPHvhADfDA8vmqx+E4DTTkrcJi2VZyzzxPTcmZ0ksvT5tZNGbLLG+5DQHGEn+UtGr+8PNNSUD+3AGuqZKWcpZwaPjzOxjUwZojc40yu/O/kDP5fKGuxKI20WtYqL1uY29hSGTxgT8XnkRuQ5A0immO9e4kZjDBoLipo0fpqzrZDW5+v6NKfR8I1coOYlTXmhSeGlyMgHcCMhqKI+1Si9x7m7Vx2xhWjr4KjOoud8gIpxRcEgNgajHISvN6jgHg3IEZNeg7ZfHQzxuFlVJZ8HMHdmlmkjQ5oV8f8ekpqEhl/D2/gEoi3hiPQFihs/hBN8z9nSHKZ848sMh515H80f60moDhnY4DnrOXyrXVoOflKOLNlEeFBPl/wHfgXLzBzBBXeafGioIBEiuLAjL5oQsa+nbMfLuLoUHUj+R5sBaYemN6FPycAl4U2fAgrLsTRPfwFAwJ7m+f+Ki5GWk64ybtQmb1KSHr92/IFVkoLDf2o+tbt1LrTQxMKVRnBQ19DgkXULlwbxvsik1KhrZ2S1PONY3DjVEcXvB7NCXi0sSKQwAFrAHZD50Mh3+PqJR5OcDqVpdHkdbnKsCRfSLsbsTIsEzuRP
  template:
    metadata:
      name: db-secret
      namespace: business
